[package]
name = "microservice_demo_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
reqwest = { version = "0.11", features = ["json"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
warp = "0.3.6"
