openapi: 3.0.1
info:
  title: Customer Service
  description: This is a customer service demonstration in Scala, Go or Rust
  version: 0.0.2
servers:
  - url: http://localhost:8080
    description: server for local development
paths:
  /customer/{email}:
    get:
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
          example: test@dotsource.de
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: NOT FOUND
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
  /customer:
    post:
			description: Upsert a customer
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              allOf:
                - $ref: '#/components/schemas/Customer'
              required: ['email']
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: BAD REQUEST
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Customer:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
          description: ISO-8601 Date
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
    Address:
      type: object
      properties:
        streetName:
          type: string
        city:
          type: string
        zipCode:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
          enum:
            - NOT_FOUND
            - BAD_REQUEST