openapi: 3.0.1
info:
  title: Customer Service
  description: This is a customer service demonstration in Scala, Go or Rust
  version: 0.1.2
servers:
  - url: http://localhost:3030
    description: local rust (warp) server
paths:
  /customer/{email}:
    get:
      description: Read a customer
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
          example: example@test.com
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: NOT FOUND
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: Delete a customer
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
          example: example@test.com
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: NOT FOUND
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Create or update a customer
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
          example: example@test.com
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              allOf:
                - $ref: '#/components/schemas/Customer'
              required: ['email']
      responses:
        '200':
          description: A customer has been updated
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Customer'
        '201':
          description: A customer has been created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: BAD REQUEST
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Customer:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
          description: ISO-8601 Date
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
    Address:
      type: object
      properties:
        streetName:
          type: string
        city:
          type: string
        zipCode:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
          enum:
            - NOT_FOUND
            - BAD_REQUEST
            - METHOD_NOT_ALLOWED
